### ISSUE TITLE
Make Language Selection Simpler

### ISSUE THREAD

**Issue by TeaBizzy** [jacobkim9881/localization-manager#5]
Currently to modify desired translation language, users either have to comment out or worse delete the values in `lang_code.js`.

This is problematic for a few reasons, if users delete values, and later want them back they would need to re-clone the `lang_code.js` file to restore it.
Also what if the user just wants to localize to a couple languages, they must spend time removing a majority of the values to only get the languages they want.

I propose we change `lang_code.js` to have an array where the user can add the languages they want from the `langsExplain` object. `lang_code.js` will use that array to localize with the desired languages, and if that array is empty `lang_code.js` will use all languages by default.

Additionally some comments explaining how to use `lang_code.js` would help new users in operation.

**TODO**
- [x] Add an appropriately named array to `lang_code.js`.
- [x] Write conditional for `lang_code.js` to export the array above, or the `langsExplain` object if the array is empty. 
- [x] Add comments to `lang_code.js` instructing users how to select languages they desire.
- [x] Run and test for bugs / errors.

**NOTE:** I did my best to figure out how `lang_code.js` is used within the program, but my findings may be inaccurate. @jacobkim9881 if you have any insight to add, or if I have made a mistake, please comment. Thank you.

EDIT: Removed an unneeded item from the TODO.

**Comment by jacobkim9881** [comment]
Deleting values at `./src/lang_code` is bothersome to get fewer language version json files.

This repo covers all language in `./src/lang_code`. Users could want a json file to be the one translated with all language version or the language version could be one. When one user want all the language version then current repository has no problem but if the user want one language version json file then it could be bothersome to execute the program. Then the user should delete keys of the list at `./src/lang_code` before executing.

**Comment by jacobkim9881** [comment]
Let me brief how the `./src/lang_code` is used on the repo. The json object is exported to `./src/index.js` and used as arguments for `localizeObj` function at line 52 and `writeJson` function at line 64 of `./src/index.js` each.

`./src/lang_code` is exported to `./src/language-number.js` and then exported to `./src/src.sh` as object entries length to let decide how many times to execute `index.js` file for each language version at line 34 in `exe.sh`.  `./src/language-number.js` is created and added after this repo is build.

1. `./src/lang_code` is exported to `./src/language-number.js`.
2. `./src/language-number.js` is exported to `./src/src.sh`.
3. `./src/src.sh` is used as `$LangNumber` at line 34 in `exe.sh`.

PS.
So `./src/lang_code` is exported 2 times.

**Comment by TeaBizzy** [comment]
Hi Jacob, thanks for the comments and extra insight into how `./src/lang_code` works within the repo.

I will give this enhancement a shot today and see if I can get it to work.

**Comment by jacobkim9881** [comment]
Sure. If you want any other brief to proceed then don't be hesitant to ask.

**Comment by jacobkim9881** [comment]
This issue solved by #7.
